[project]
name = "hello-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.67.0",
    "dotenv>=0.9.9",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
]
